name: Bash Script Lint & Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x iit_fee_calculator.sh

      - name: Run the script (basic test)
        run: echo -e "GEN\n600000" | ./iit_fee_calculator.sh

      - name: Lint with ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          check_together: true
